json.logger.base.path=target/logs/json
json.reader.base.path=target/logs/json
json.writer.base.path=target/logs/json
test.data.base.path=target/logs/test-data/
test.data.fallback.path=fallback/
test.data.resource.path=src/main/resources/
upload.base.path=uploads/
account.mapping.fallback.path=fallback/account-mapping/field-type-fallbacks.json
locators.template.output.dir=locators/


# Add more as needed
