extent.reporter.spark.start=true
extent.reporter.spark.out=src/main/resources/ExtentReports/SparkReports/TestCasesReport.html
extent.reporter.spark.base64imagesrc=true
extent.reporter.spark.vieworder=dashboard,test,category,exception,author,device
systeminfo.os=Window
systeminfo.user=Attinderveer Singh
systeminfo.server=Jackson