# Quick Search Elements
QUICK_SEARCH_INPUT = //input[@data-placeholder='%s']
QUICK_SEARCH_BUTTON = //button[span[text()='Search']]

# Default Reports Tiles
ACCOUNT_MAPPING_DEFAULT_REPORTS_TILE = //div[@id='AccountMapping_%s']/button

# Import Records Drop-Down
IMPORT_RECORDS_TRIGGER = //button[span[contains(text(),'Import Records')]]
IMPORT_RECORDS_LIST = //button[button[contains(text(),'%s')]]

# Import Records Popup Common elements
IMPORTS_RECORDS_OVERLAY = //div[@id='mainModal' and @class='modal fade show']
YOU_CAN_ONLY_SELECT_CSV_OR_EXCEL_FILE = //div[@*= 'select_only_csv_or_excel']
IMPORT_RECORDS_IFRAME = (//div[@class='csvbox-holder']/iframe)[1]
IMPORT_RECORDS_POPUP_NAVIGATION_BUTTON = //div[@id='direction-buttons']/button[contains(text(),'%s')]
IMPORT_RECORDS_POPUP_VIEWS_HEADING = //div[@class='modal-content']//*[contains(text(),'%s')]

#Views:
# Import Records View
DROP_FILES_HERE_OR_CLICK_TO_UPLOAD = //input[@type='file']



# Import Records Table
IMPORT_RECORDS_TABLE = //table[@id='outputTable' and .//tr]
IMPORT_RECORDS_TABLE_HEADERS = //table[@id='outputTable']//thead//th/div
IMPORT_RECORDS_TABLE_ROWS    = //table[@id='outputTable']//tbody//tr
IMPORT_RECORDS_TABLE_COLUMNS = //table[@id='outputTable']//tr/td[%s]
IMPORT_RECORDS_TABLE_CELL = //table[@id='outputTable' and .//tr]//tbody/tr[%s]/td[%s]
IMPORT_RECORDS_TABLE_INPUTS = //table[@id='outputTable' and .//tr]//tfoot//input
IMPORT_RECORDS_TABLE_ADD_ROW_BUTTON = //td/button[contains(text(),'%s')]

