package core.resolvers.locator.sync;

import core.resolvers.locator.sync.LocatorTemplateGenerator.LocatorKey;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Creates a new properties template file or merges missing keys into an existing one.
 *
 * <p>Merge-with-preserve invariant: existing key-value pairs are never modified.
 * Only absent keys are added. The file structure (comments, blank lines, ordering) is
 * preserved for existing content; new keys are appended to their section.</p>
 */
final class LocatorTemplateWriter {

    static final String LINE_SEP = System.lineSeparator();

    /** Writes a brand-new properties file with all expected keys blank. */
    void writeNew(Path file, String pageSimpleName, List<LocatorKey> keys) throws IOException {
        Files.createDirectories(file.getParent());
        Files.writeString(file, buildNewContent(pageSimpleName, keys), StandardCharsets.UTF_8);
    }

    /**
     * Appends missing keys to the existing file.
     *
     * @return {@code true} if the file was modified, {@code false} if every expected key was already present
     */
    boolean mergeInto(Path file, List<LocatorKey> allKeys, Set<String> existingKeys) throws IOException {
        List<LocatorKey> missing = allKeys.stream()
            .filter(k -> !existingKeys.contains(k.key()))
            .toList();
        if (missing.isEmpty()) return false;

        List<String> lines = new ArrayList<>(Files.readAllLines(file, StandardCharsets.UTF_8));
        for (LocatorKey lk : missing) {
            insertKey(lines, lk.enumSimpleName(), lk.key());
        }

        String content = String.join(LINE_SEP, lines);
        if (!content.endsWith(LINE_SEP)) content += LINE_SEP;
        Files.writeString(file, content, StandardCharsets.UTF_8);
        return true;
    }

    private void insertKey(List<String> lines, String enumSimple, String key) {
        String sectionHeader = "# --- " + enumSimple + " ---";

        // Find section header
        int sectionStart = -1;
        for (int i = 0; i < lines.size(); i++) {
            if (lines.get(i).trim().equals(sectionHeader)) {
                sectionStart = i;
                break;
            }
        }

        if (sectionStart >= 0) {
            // Advance to the last key line in this section
            int lastKeyLine = sectionStart;
            for (int i = sectionStart + 1; i < lines.size(); i++) {
                String l = lines.get(i).trim();
                if (l.startsWith("# ---")) break;
                if (!l.isEmpty() && !l.startsWith("#")) lastKeyLine = i;
            }
            lines.add(lastKeyLine + 1, key + "=");
        } else {
            // New section — append at end
            if (!lines.isEmpty() && !lines.get(lines.size() - 1).isBlank()) {
                lines.add("");
            }
            lines.add("# --- " + enumSimple + " ---");
            lines.add(key + "=");
        }
    }

    private String buildNewContent(String pageSimpleName, List<LocatorKey> keys) {
        LinkedHashMap<String, List<LocatorKey>> bySection = new LinkedHashMap<>();
        for (LocatorKey lk : keys) {
            bySection.computeIfAbsent(lk.enumSimpleName(), k -> new ArrayList<>()).add(lk);
        }

        StringBuilder sb = new StringBuilder();
        sb.append("# ").append(pageSimpleName).append(" — locators\n");
        sb.append("# Generated by LocatorSyncCli. Fill XPath values only. Do not edit keys.\n");
        sb.append("# Re-run --sync to add new constants. Use --prune to remove orphan keys.\n");

        for (Map.Entry<String, List<LocatorKey>> section : bySection.entrySet()) {
            sb.append("\n# --- ").append(section.getKey()).append(" ---\n");
            for (LocatorKey lk : section.getValue()) {
                sb.append(lk.key()).append("=\n");
            }
        }
        return sb.toString();
    }
}
