# Dynamic result item (match by visible text)
SEARCH_RESULT_LOCATOR=(//mat-option[span/*[contains(normalize-space(text()),'%s')]] | //mat-option[contains(normalize-space(text()),'%s')])[1]
# Partner Information (Vendor user only)
# Input field
SELECT_YOUR_PARTNER_SEARCH_BAR=//input[@id='walkme_partnerInfo_input']

# New Registration Navigation Buttons (Back, Next, Save and Continue)
PARTNER_INFO_NAVIGATION_BUTTONS=//button[contains(@id,'walkme_partnerInfo_%s')]
PROGRAM_SELECTION_NAVIGATION_BUTTONS=//button[contains(@id,'walkme_selectProgram_%s')]
OPPORTUNITY_INFO_NAVIGATION_BUTTONS=//button[contains(@id,'walkme_oppInfo_%s')]
SALES_REP_NAVIGATION_BUTTONS=//button[contains(@id,'walkme_salesRep_%s')]

# Program Selection
PROGRAM_SELECTION=//input[@id='%s-input']

# Opportunity Information
OPPORTUNITY_INFORMATION=(//input[@formcontrolname='%s'] | //textarea[@formcontrolname='%s'])

# SALES REP & END CUSTOMER INFORMATION
# Input field
SALES_REP_SEARCH_BAR=(//input[@formcontrolname='salesRepAutocompleteControl'])[2]
END_CUSTOMER_PRIMARY_CONTACT_SEARCH_BAR=//input[@formcontrolname='customerContactAutocompleteControl']
END_CUSTOMER_COMPANY_SEARCH_BAR=//input[@formcontrolname='customerAutocompleteControl']


#

