# Default Reports Tiles
DEFAULT_REPORTS_TILE = //div[@id='Registrations_DefaultReports_%s']/button

# Row 3 Dots options
3DOTS_BUTTON = //table//tbody/tr[contains(@class,'main') and not(contains(@class,'hidden'))]//button
3DOTS_OPTIONS_LIST = //button[contains(@id,'%s')]